name    'velaluqa-tinytinyrss'
version '0.0.1'
source  'https://github.com/velaluqa/puppet-tinytinyrss'
author  'Arthur Leonard Andersen'
license 'GPLv3'
summary 'Puppet Tiny Tiny RSS Module'
description 'Module to install PhpMyAdmin using puppet.'
project_page 'https://github.com/velaluqa/puppet-tinytinyrss/'
dependency 'torrancew/cron', '>= 0.1.0'
